# Generated by Django 4.0.6 on 2022-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSunvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ocorrencia'),
        ),
    ]
