# Generated by Django 4.0.6 on 2022-07-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSunvey', '0002_alter_ocorrencia_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicençadeSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('numerodeSerie', models.CharField(blank=True, max_length=255, null=True)),
                ('Observaçoes', models.TextField(blank=True, null=True)),
                ('Produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeoSunvey.produto')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeoSunvey.cliente')),
            ],
        ),
    ]
