# Generated by Django 4.0.6 on 2022-07-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSunvey', '0003_licençadeserie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licençadeserie',
            options={'verbose_name_plural': 'Licenças de Série'},
        ),
        migrations.CreateModel(
            name='LicençaGeoMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('descriçao', models.TextField(blank=True, null=True)),
                ('Equipamento_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeoSunvey.cliente')),
            ],
            options={
                'verbose_name_plural': 'Licenças do GGO',
            },
        ),
    ]
