# Generated by Django 4.0.6 on 2022-07-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSunvey', '0005_licençasurpad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licençasurpad',
            options={'verbose_name_plural': 'Licenças do SurPad'},
        ),
        migrations.CreateModel(
            name='LicençaXPAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licença', models.CharField(blank=True, max_length=255, null=True)),
                ('Transfer_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Equipamento_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.TextField(blank=True, null=True)),
                ('descriçao', models.TextField(blank=True, null=True)),
                ('data_de_entrega', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeoSunvey.cliente')),
            ],
            options={
                'verbose_name_plural': 'Licenças do X-PAD',
            },
        ),
    ]
