# Generated by Django 4.0.6 on 2022-07-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSunvey', '0006_alter_licençasurpad_options_licençaxpad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicençaSURVX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licença', models.CharField(blank=True, max_length=255, null=True)),
                ('Transfer_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Equipamento_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeoSunvey.cliente')),
            ],
            options={
                'verbose_name_plural': 'Licenças do X-PAD',
            },
        ),
    ]
