# Generated by Django 4.0.6 on 2022-07-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSunvey', '0007_licençasurvx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licençasurvx',
            options={'verbose_name_plural': 'Licenças do SurvX Sanding'},
        ),
        migrations.CreateModel(
            name='LicençaAplitop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licença', models.CharField(blank=True, max_length=255, null=True)),
                ('data_de_ativacao', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeoSunvey.cliente')),
            ],
            options={
                'verbose_name_plural': 'Licenças do Aplitop',
            },
        ),
    ]
