# Generated by Django 4.0.6 on 2022-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSunvey', '0008_alter_licençasurvx_options_licençaaplitop'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo_coletora', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number_base', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number_rover', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number_coletora', models.CharField(blank=True, max_length=255, null=True)),
                ('Serial_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Aplicativo', models.CharField(blank=True, max_length=255, null=True)),
                ('Número_do_Kit', models.CharField(blank=True, max_length=255, null=True)),
                ('Equipment_ID', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kit de Locacao',
            },
        ),
    ]
